spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.bytecode.provider=bytebuddy
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

app.jwt.secret=${JWT_SECRET:bXktc3VwZXItc2VjcmV0LWp3dC1rZXktZm9yLW1hdGNodm9sbGV5LTI0}
app.jwt.access-token-expiration=900000
app.jwt.refresh-token-expiration=2592000000